APPLY_FIXES: all
ENABLE:
  - ACTION
  - DOCKERFILE
  - GHERKIN
  - JSON
  - MARKDOWN
  - REPOSITORY
  - SPELL
  - YAML
DISABLE_LINTERS:
  - REPOSITORY_DEVSKIM
  - REPOSITORY_GITLEAKS
  - REPOSITORY_KICS
  - REPOSITORY_SEMGREP
  - JSON_JSONLINT
  - SPELL_CSPELL
  - SPELL_PROSELINT
DISABLE_ERRORS_LINTERS:
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - SPELL_LYCHEE
PRINT_ALPACA: false
SHOW_SKIPPED_LINTERS: false
SARIF_REPORTER: true
