---
name: Continuous Integration

on:
  workflow_call:
    inputs:
      version:
        description: "Version"
        required: true
        type: string

permissions: {}

jobs:
  upgrade-pack:
    name: Build Upgrade Pack
    runs-on: [ubuntu-latest]
    container: ghcr.io/philips-software/amp-devcontainer-cpp:v6.0.2@sha256:36afaaa5ba4bc4e9bb471012db9733c26a210e315ddb33600f73bb9532b02a25 # 6.0.2
    steps:
      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: HostInstall
      - id: convert-version
        run: echo "${{ inputs.version }}" | sed -e 's/v/version=/' -e 's/\/merge//' >> $GITHUB_OUTPUT
      - run: tar -zxvf Postmaster-${{ steps.convert-version.outputs.version }}-Linux.tar.gz
      - run: mkdir install
      - run: mv Postmaster-${{ steps.convert-version.outputs.version }}-Linux/* install/
      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: postmaster
      - run: tar -zxvf Postmaster-${{ steps.convert-version.outputs.version }}-Generic-ELF.tar.gz
      - run: cp -r Postmaster-${{ steps.convert-version.outputs.version }}-Generic-ELF/* install/
      - run: install/bin/postmaster.upgrade_pack_builder --app=install/bin/postmaster.postmaster_stm32f407.hex --output=Postmaster-${{ inputs.version }}.upg
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: UpgradePack
          path: Postmaster-${{ inputs.version }}.upg
